language: ruby
sudo: false
gemfile:
  - Gemfile
rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.1
env:
  matrix:
    - DB=sqlite3
matrix:
  fast_finish: true
branches:
  only:
    - master
notifications:
  email: false
